using Godot;
using FSharpGodot;

public partial class HUD : FSharpHud {
/* It seems, to emit a signal named X, we must declare delegate XEventHandler. See:
https://docs.godotengine.org/en/stable/getting_started/step_by_step/signals.html#custom-signals
*/
	[Signal]
	public delegate void StartGameEventHandler();

	[Signal]
	public delegate void ShowAttractScreenEventHandler();

/* Godot will not call the inherited methods, so we must override them and then call them explicitly. We do not know why. */
	new private void start_button_pressed_handler () { base.start_button_pressed_handler (); }
	new private void message_timer_timeout_handler () { base.message_timer_timeout_handler (); }
}

/* We right-clicked "FSharpHud" in "public partial class HUD : FSharpHud" and selected "Go to Definition". A tab opened named "[metadata] FSharpHud.cs" that contains the following.
#region Assembly fsharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// fsharp.dll
#endregion

using Godot;
using Microsoft.FSharp.Core;

namespace FSharpGodot
{
	[CompilationMapping(SourceConstructFlags.ObjectType)]
	public class FSharpHud : CanvasLayer
	{
		public FSharpHud();

		public override void _Process(double delta);
		public override void _Ready();
	}
}
(end)

It seems this is generated by Codium.

20240215
- After we restarted the VM, the correct metadata were generated. We do not know why.
- Calling, for example, base.UpdateScore(1) from HUD.cs now does not show an error.
- We did not try running dotnet build when this was happening, so it might have been a bug in Codium.
- However, Godot still will not call start_button_pressed_handler () in the base class.
- We ran dotnet clean/dotnet build. The metadata is still outdated.
- Restarting Codium regenerates the metadata.
*/

/* We tried setting the following in hud.tscn but it did not work.
[ext_resource type="Script" path="res://fsharp/FSharpHud.fs" id="2"]
[connection signal="pressed" from="StartButton" to="FSharpHud" method="start_button_pressed_handler"]
[connection signal="timeout" from="MessageTimer" to="FSharpHud" method="message_timer_timeout_handler"]

It seems Godot does not recognize an F# file as a script.
*/
